baseURL = "https://www.itsmejuha.co/"
languageCode = "en-us"
title = "Juha Liikala | Front-End Engineer | Oulu, Finland"
theme = "itsmejuhaco"

enableEmoji = true

[permalinks]
	fixed = ":title/"
	blog  = ":slug/"

[params]
	author = "Juha Liikala"
	description = "Juha Liikala is a developer, designer and blogger who has been building websites and software for a living since 2001."
	coverimage = "https://itsmejuha.co/images/juhaheader.jpg"
	latestpostscount = 5
	title = "Juha Liikala - Developer, Designer and Blogger from Oulu, Finland"
	email = "sayhello@itsmejuha.co"
	twitterUrl ="https://twitter.com/juhaliikala/"
	instagramUrl = "https://www.instagram.com/nomadcouch/"
	linkedinUrl = "https://www.linkedin.com/in/juhaliikala"
	producthuntUrl = "https://www.producthunt.com/@juhaliikala"
	unsplashUrl = "https://unsplash.com/@juhaliikala"
	mediumUrl = "https://medium.com/@juhaliikala"
	facebookUrl = "https://www.facebook.com/juhaliikala"
	avatar = "https://itsmejuha.co/images/avatar_400x400.jpg"
	FBPage = "https://www.facebook.com/itsmejuhaco/"
	FBAuthor = "https://www.facebook.com/JuhaLiikala/"