baseURL = "/"
languageCode = "en-us"
title = "Juha Liikala | Front-End Engineer | Oulu, Finland"
theme = "itsmejuhaco"

enableEmoji = true

[permalinks]
	fixed = ":title/"
	blog  = ":slug/"

[params]
	author = "Juha Liikala"
	description = "Personal online home of Juha Liikala"
	coverimage = "https://itsmejuha.co/images/juhaheader.jpg"
	latestpostscount = 5
	title = "Juha Liikala"
	email = "sayhello@itsmejuha.co"
	twitter ="juhaliikala"
	instagram = "nomadcouch"
	linkedin = "juhaliikala"
	facebook = "juhaliikala"
	avatar = "https://itsmejuha.co/images/avatar_400x400.jpg"
	FBPage = "https://www.facebook.com/itsmejuhaco/"
	FBAuthor = "https://www.facebook.com/JuhaLiikala/"